### ISSUE TITLE
Support bridging Discord messages from other bots in unencrypted DM rooms

### ISSUE THREAD

**Issue by ThePolishLemon** [mautrix/discord#106]
Lemme just give u an example so u can see what I'm talking about 
![Screenshot_20230718_141618_Discord](https://github.com/mautrix/discord/assets/82435316/2991f24e-2e39-42f6-8d70-580842cc308e)
![Screenshot_20230718_141610_Element](https://github.com/mautrix/discord/assets/82435316/946d3b52-8166-4ec8-b0f2-369d3baf8081)

**Comment by tezlm** [comment]
this already works if you have access to clyde

**Comment by ThePolishLemon** [comment]
I do, Clyde works just not in other people's dms and thts what this feature req is about, you can see the images i attached one from the discord client and one from element, on discord Clyde is fully functional in the DM, in element he doesn't show up at all

**Comment by tezlm** [comment]
try inviting clyde to your dm

**Comment by tulir** [comment]
Already works fine, it just can't currently get invited in unencrypted DM rooms because the bridge bot isn't there to invite it.

**Comment by ThePolishLemon** [comment]
Ok that did make it work thank you, I can now annoy ppl with Clyde without having to switch clients
