### ISSUE TITLE
Permission escalation issue with multiple user using the same matrix server

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [mautrix/discord#112]
I have a discord server where I'm not an admin and I can only see a few channels. a friend of mine has access to some more channels.

We both use the same matrix server, and we both have our accounts linked using mautrix-discord.

In matrix, I can see the channels he should only be able to see.

Since I get access to information I should not have access to, this is privilege escalation.

**Comment by tulir** [comment]
Duplicate of #107

**Comment by Marc-Pierre-Barbier** [comment]
yea but #107 is closed and the bug remain
