### ISSUE TITLE
Option for separate media repo url

### ISSUE THREAD

**Issue by tezlm** [mautrix/discord#116]
I use [matrix-media-repo](https://github.com/turt2live/matrix-media-repo), so I need to be able to upload to a separate address instead of the main homeserver address.

I can set the address to the public-facing url instead of localhost, but that would cause unnecessary overhead.

**Comment by tulir** [comment]
You should just have an internal (non-tls) endpoint in your reverse proxy, otherwise the bridge would need advanced custom routing capabilities to support other types of workers
