### ISSUE TITLE
Replies from discord without edits do not show up correctly in Element Android

### ISSUE THREAD

**Issue by Zwelf** [mautrix/discord#117]
Messages with replies on discord don't get shown in Element Android. Element Web displays them fine.

### Screenshots:
<details>

| Element desktop | Element Android | Element Android long press on message |
| --- | --- | --- |
| ![element-web](https://github.com/mautrix/discord/assets/9964758/2c02df2e-5e47-406b-bc00-433a19f6201f) | ![element-android](https://github.com/mautrix/discord/assets/9964758/4be5aa2d-9b10-46af-969f-1122aa77dc6b) | ![element-android-select](https://github.com/mautrix/discord/assets/9964758/10b209e7-cf90-48bc-a396-e98ed6e76e67) |

</details>

### Links message on matrix/discord:
* [Direct link to message on matrix](https://matrix.to/#/!XL64iBrBYNLL1HSuSx:ddnet.org/$5ouDCBdBz1NKmyTFwft3SpJ2iOVEXIndXrqGEVJk6fg?via=ddnet.org&via=matrix.org&via=tchncs.de)
* [Link to message in discord archive](https://archive.strct.cc/ddnet/2023-08-27/developer.html#chatlog__message-container-1145397426832810074)

### Source

Reply message, doesn't get shown in element-android:
<details>

```
{
  "content": {
    "body": "on 2023-08-20",
    "com.beeper.linkpreviews": [],
    "com.beeper.per_message_profile": {
      "avatar_url": "mxc://discord-media.mau.dev/avatars|893454802464411689|bc46721b305d4e67fb352e26edfdedcf.png",
      "displayname": "Jupstar ✪",
      "is_multiple_users": false
    },
    "fi.mau.discord.guild_member_metadata": {
      "avatar_id": "",
      "avatar_mxc": "",
      "avatar_url": "",
      "nick": "Jupstar ✪"
    },
    "m.mentions": {
      "user_ids": [
        "@discord_436500869547163664:ddnet.org"
      ]
    },
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$IAr9CJ7yeouayQCF-OivuExmdARyDjMRTML-5agvltQ"
      }
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1693154427105,
  "room_id": "!XL64iBrBYNLL1HSuSx:ddnet.org",
  "sender": "@discord_893454802464411689:ddnet.org",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$5ouDCBdBz1NKmyTFwft3SpJ2iOVEXIndXrqGEVJk6fg",
  "user_id": "@discord_893454802464411689:ddnet.org"
}
```
</details>

Reply message with edit. Gets shown correctly in Element Android:

<details>

```
{
  "content": {
    "body": "* i think you can use para zoom instead of normal para if ur client is updated",
    "m.mentions": {},
    "m.new_content": {
      "body": "i think you can use para zoom instead of normal para if ur client is updated",
      "com.beeper.linkpreviews": [],
      "com.beeper.per_message_profile": {
        "avatar_url": "mxc://discord-media.mau.dev/avatars|513871312347987968|9a96d8f1122bf08d2214d4b4718d3554.png",
        "displayname": "louis",
        "is_multiple_users": false
      },
      "fi.mau.discord.guild_member_metadata": {
        "avatar_id": "",
        "avatar_mxc": "",
        "avatar_url": "",
        "nick": "louis"
      },
      "m.mentions": {},
      "msgtype": "m.text"
    },
    "m.relates_to": {
      "event_id": "$8RWfmuPUAEFmZiw0EpflQc5ICZLGe1spZ8ySf5BBMFs",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1693138578338,
  "room_id": "!XL64iBrBYNLL1HSuSx:ddnet.org",
  "sender": "@discord_513871312347987968:ddnet.org",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$CuFD8zYyObVFAHgH-YsC7-lPojQlkBN_673DJ3eXD78",
  "user_id": "@discord_513871312347987968:ddnet.org"
}
```
</details>

**Comment by tulir** [comment]
Element Android doesn't support rendering replies properly

**Comment by Zwelf** [comment]
vector-im/element-android#8460 😞

**Comment by tulir** [comment]
Element X's (both android and ios) do have proper reply rendering btw

**Comment by zouppen** [comment]
I would be very happy if the reply fallback feature is implemented to this bridge similarly as it is in mautrix-telegram for example.

Element X is still not very usable as an only client (missing essential features like changing a password!) and I'd probably need to wait another year before it's ready for everyday use. Sad, but implementing a workaround would greatly help Matrix adoption.
