### ISSUE TITLE
Automatically create puppets that represent the users on the Discord side

### ISSUE THREAD

**Issue by TomTheDragon** [mautrix/discord#121]
I recently started looking into ways to bridge a Telegram group over to a Matrix room and i stumbled over mautrix-telegram.
I was really surprised how well it works and i partially liked the feature, that it can create puppets inside a matrix room, to represent the telegram users on the other side.
It would be great if we could have a similar functionally inside mautrix-discord as well, since it would also eliminate the constant messages about changed names and avatars.

**Comment by tulir** [comment]
That's how all bridges work

**Comment by TomTheDragon** [comment]
When i setup a bridge, only one puppet is in my room, which constantly changes its name and icon, when ever a messages from a different user gets received
On mautrix-telegram i do see as many puppets as there are users on the telegram side, so there is no need to keep changing all the time
