### ISSUE TITLE
Creating a private message room to a bridged matrix user doesnt send messages to the discord user

### ISSUE THREAD

**Issue by davidovski** [mautrix/discord#123]
When you start a private message to a bridged user via matrix, messages that are sent are not bridged to discord. 
The current workaround that I have been using is using discord to start the dm, which creates the matrix room which correctly bridges messages.

**Comment by tulir** [comment]
That's "Private chat creation by inviting Matrix puppet of Discord user to new room" in the [roadmap](https://github.com/mautrix/discord/blob/main/ROADMAP.md). Not sure if it'll ever be implemented, I've heard discord will think you're a spammer if you start DMs

**Comment by tezlm** [comment]
When accepting a friend request on discord, it creates a dm room. I tried sending a message and got this response:

> ⚠ Your message was not bridged: Captcha error

so I'm pretty sure it's not possible unless you send at least one message from discord first.

**Comment by davidovski** [comment]
Thats understandable. The only issue with starting a dm through matrix is that the messages sent via discord are not bridged; I've been in several situations where I've forgotten why I opened that DM in the first place. Is there a way to have your own messages bridged in DMs?

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/double-puppeting.html
