### ISSUE TITLE
Edited messages don't bridge in replies

### ISSUE THREAD

**Issue by scriptod911** [mautrix/discord#130]
Version: 0.6.4
Bridge method: Webhook relay

How to re-create:
1. Send a message in matrix
2. Reply to it
3. Edit the original

I expect for the embed to change to the new message.

![image](https://github.com/mautrix/discord/assets/70215102/1e4ed3ae-c51f-447c-9da2-26b66be273d3)
![imag2](https://github.com/mautrix/discord/assets/70215102/ba4a43c2-c46c-4d63-9c99-172ace6dcd78)

**Comment by tulir** [comment]
Probably not going to do that, lots of effort for little gain

**Comment by scriptod911** [comment]
Also, this is similar to an embed issue, because in when someone sends a message in Matrix, and someone replies in discord to that message, and that person deletes their message from Matrix, the message stays as an embed in discord. Which means deleted messages are viewable in embeds. I'd assume this is more important.
