### ISSUE TITLE
Custom emoji reactions show up as "mxc://..." rather than as the actual icon

### ISSUE THREAD

**Issue by ToxicFrog** [mautrix/discord#133]
In normal text the custom emoji show up as expected, in reactions they show up as text. For a recent example, the reaction server-side is `:lel:` but as displayed in matrix, the reaction button displays (a truncated form of) the text `mxc://ancilla.ca/AXUz2UOSJQBxdvRtjTEJ1E4k9QUuMPWM` and the aria-label is `[list of users] reacted with mxc://ancilla.ca/AXUz2UOSJQBxdvRtjTEJ1E4k9QUuMPWM` rather than showing the react name.

Setting `custom_emoji_reactions: false` behaves as expected: the reaction shows up as the textual form `:lel:`.

**Comment by morguldir** [comment]
If your client doesn't support custom emojis that's expected

![image](https://github.com/mautrix/discord/assets/21371374/672cd894-fd75-4ca9-a997-855635313ea9)

**Comment by tulir** [comment]
Sounds like you already found the config option, so not sure what this issue is for. The default behavior is images, and the config option is there to send them as text shortcodes if you don't use a client that supports custom reaction images.

**Comment by ToxicFrog** [comment]
> If your client doesn't support custom emojis that's expected
>
Aah, so this is a client issue? Is that an Element screenshot? If so, mine doesn't have that option, but if they're working on it, I can wait.

Sorry for the noise.
