### ISSUE TITLE
Direct Media Access not working, new URL hash

### ISSUE THREAD

**Issue by kimabjorkede** [mautrix/discord#137]
It seems that Discord has added some kind of hash to image URLs, and refuses to show the image without it.

This is the link the Discord client gets. Which works.
`https://media.discordapp.net/attachments/1180902645825814612/1208947370943971408/IMG_4938.jpg?ex=65e522fa&is=65d2adfa&hm=d007fc304048ba0b030a674f9bcf922e61fedc7a6233616ad467c5a1adb79024&=&format=webp&width=464&height=619`

This is the link that the bridge gets, and is redirected to by Nginx.
`https://cdn.discordapp.com/attachments/1180902645825814612/1208947370943971408/IMG_4938.jpg`

If you try it out yourself you'll see that only the top one wants to load.

----------
Edit.
`https://media.discordapp.net/attachments/1180902645825814612/1208947370943971408/IMG_4938.jpg` does not work either.

**Comment by morguldir** [comment]
Update your bridge and check out https://docs.mau.fi/bridges/go/discord/direct-media.html
