### ISSUE TITLE
rooms not correctly assigned as DMs on fluffychat

### ISSUE THREAD

**Issue by IceMinePenguin** [mautrix/discord#138]
If I DM or receive a DM from someone new on discord, and the first client i look at for matrix is fluffychat android, it's called "Group with [username]" and is marked as a regular room, not a DM. To fix this, i have to elevate my permissions with `!discord set-pl` 100 and then rename the room to just the username, then go on element web and the bridge turns it into a DM. After that, it appears as a DM fine in fluffychat.

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/troubleshooting.html#why-are-direct-messages-showing-up-under-rooms-instead-of-people
