### ISSUE TITLE
The bridge keeps inviting itself into all sorts of rooms

### ISSUE THREAD

**Issue by TomTheDragon** [mautrix/discord#159]
I am not quite sure why but recently the bridge started to invite itself into all sorts of rooms i am in, including foreign rooms i dont own and it keeps doing that until you ban it in that room.
This also happens with other bridges too, which is in my case the telegram, the signal and the twitter one.

**Comment by tulir** [comment]
That should only happen if you misconfigure the registration file or if your homeserver is otherwise sending random events to the bridge

**Comment by TomTheDragon** [comment]
I think i solved it, i did base my registration files on this https://docs.mau.fi/bridges/general/double-puppeting.html#automatically but i still had something defined in "url:"
