### ISSUE TITLE
Option to post link to images / videos instead of downloading onto homeserver

### ISSUE THREAD

**Issue by aflyingpumpkin** [mautrix/discord#16]
This helps to reduce the amount of storage space used by the bot. Implementing this on a per bridged guild / room level would also be useful, to allow backing up of more sensitive content while avoiding large amounts of system storage taken up by the bridge if a meme channel on a popular guild is bridged.

**Comment by ToyKeeper** [comment]
This could also help improve another issue.  Sometimes the original filename isn't available after downloading files onto the homeserver, so files are only known by ID instead of name.  Using the original URL (or at least making it available somehow) could provide more info about the file.

**Comment by obj-obj** [comment]
Yeah, especially because Element usually embeds the image/video (although it's extremely small, and you need to click on it for it to be any reasonable size)

**Comment by tulir** [comment]
Bypassing the media repo is now supported (https://docs.mau.fi/bridges/go/discord/direct-media.html), sending links probably won't be
