### ISSUE TITLE
Direct Media server downloads (sometimes) result in M_TOO_LARGE

### ISSUE THREAD

**Issue by North-West-Wind** [mautrix/discord#162]
With `direct_media` enabled, sometimes images cannot be viewed. By checking the network request, the response for a request is 502 with a message.

An example of Cinny sending a GET request to `https://matrix.northwestw.in/_matrix/client/v1/media/download/mautrix-discord.northwestw.in/8J-QiERJU0NPUkQBAQ5kKvLIhABYEc3ksnjAAD0RzeSyakAQW7BgIOoL5KW2wBrYMr0eTnY?allow_redirect=true`
```json
{
  "errcode": "M_TOO_LARGE",
  "error": "Requested file is too large > 459 bytes"
}
```

Weirdly, if I go directly to the media server (replacing request host with media server name), the URL does redirect to the correct Discord attachment. In addition to that, the problem fixes itself after a while and the media can be loaded in all clients.

**Comment by tulir** [comment]
That's a synapse bug which should already be fixed
