### ISSUE TITLE
Chowning volumes wrongly

### ISSUE THREAD

**Issue by VetheonGames** [mautrix/discord#165]
Hey there,

We run Matrix Synapse in a Docker Stack alongside your Matrix Bridge for Slack and for Discord, as well as your bot.

The bridge for Slack and Discord run from the same docker-compose.yml as Synapse, Coturn, and PostgreSQL, and it shares it's Postgres instance with Synapse.

However, every time I stop/start the stack, the mautrix discord data volume gets chowned to some random user, and breaks the entire Matrix stack, causing synapse to fail to start at all.

Is there a way for me to stop it from changing it's own permissions? Because its doing it wrong.

**Comment by VetheonGames** [comment]
> That's an issue in your setup, not the bridge.
> 
> Anyway, the run command can be overridden safely, or the user can be changed by setting the appropriate environment variables

Could you tell me what the environment variables are, or perhaps link me to the docs page that contains a list of all of them? I've not been able to find it in the docs despite hours of searching

**Comment by tulir** [comment]
https://github.com/mautrix/discord/blob/main/docker-run.sh
