### ISSUE TITLE
guilds command not mentioned in help message

### ISSUE THREAD

**Issue by spantaleev** [mautrix/discord#18]
The help message is currently like this:

> This is your management room: prefixing commands with !discord is not required.
> 
> # Unclassified
> **delete-all-portals** - Delete all portals.
> 
> # General
> **cancel** - Cancel an ongoing action.
> **help** - Show this help message.
> **version** - Get the bridge version.
> 
> # Authentication
> **login** - Link the bridge to your Discord account by scanning a QR code.
> 
> # Administration
> **discard-megolm-session** - Discard the Megolm session in the room

The `guilds` command was not mentioned anywhere. I had to discover it from your [Authentication docs page](https://docs.mau.fi/bridges/go/discord/authentication.html).

**Comment by tulir** [comment]
The help command only includes commands that you have access to

**Comment by spantaleev** [comment]
I see. Maybe it should print `help` again after successfully authenticating me?

It could also tell me:

> Successfully authenticated as ...
>
> Your direct messages are being bridged now.
> You may also wish to bridge some guilds via the `guilds` command.
>
> Now that you are authenticated, you can also access other features. Send `help` again to see what they are.
