### ISSUE TITLE
Convert discord mentions to matrix mentions

### ISSUE THREAD

**Issue by Kitanit** [mautrix/discord#21]
situation: logged into my account discord, logged into the channel on the server and there I was mentioned, will be as a mention of the account and not me personally in matrix

**Comment by sumnerevans** [comment]
Not really sure what the issue is here... do you mean you got notified for a message that you did not expect to be mentioned in? In that case, you may have been notified due to your display name appearing in the message. There is a setting in element to disable this behavior.

**Comment by Kitanit** [comment]
> Not really sure what the issue is here... do you mean you got notified for a message that you did not expect to be mentioned in? In that case, you may have been notified due to your display name appearing in the message. There is a setting in element to disable this behavior.

No, I mean that I logged into my discord account example#1234
example#1234 was mentioned in the chat but in the matrix it looks like a mention of example#1234 and not kitanit

*at least that's what the mau telegram can do, when mentioning my telegram account it mentions matrix

**Comment by 0xDEADCADE** [comment]
I am not a go dev. This is pretty shitty code. But in case you're using a self-hosted instance, and are the only user of that instance, you should be able to make this work as a temporary solution.
Replace DISCORD_USER_ID with your Discord ID, MATRIX_ID with your Matrix ID (`@example:example.com`), and MATRIX_NAME with your Matrix username.
```diff
formatter_tag.go
@@ -260,7 +260,11 @@
        switch node := n.(type) {
        case *astDiscordUserMention:
                puppet := r.portal.bridge.GetPuppetByID(strconv.FormatInt(node.id, 10))
-               _, _ = fmt.Fprintf(w, `<a href="https://matrix.to/#/%s">%s</a>`, puppet.MXID, puppet.Name)
+               if fmt.Sprint(strconv.FormatInt(node.id, 10)) == fmt.Sprint(DISCORD_USER_ID) {
+                       _, _ = fmt.Fprintf(w, `<a href="https://matrix.to/#/%s">%s</a>`, "MATRIX_ID", "MATRIX_NAME")
+               } else {
+                       _, _ = fmt.Fprintf(w, `<a href="https://matrix.to/#/%s">%s</a>`, puppet.MXID, puppet.Name)
+               }
                return
        case *astDiscordRoleMention:
                role := r.portal.bridge.DB.Role.GetByID(r.portal.GuildID, strconv.FormatInt(node.id, 10))
```
