### ISSUE TITLE
Postfix 'Discord' to the end of usernames/room-names for more clarity

### ISSUE THREAD

**Issue by WowSuchRicky** [mautrix/discord#28]
(_I am pretty new to the Matrix ecosystem so apologies if this issue is trivial or not high quality. Happy to take your feedback and improve my issues going forward._)

When I use other bridges, the chats have the bridge name as a suffix to my chats (i.e. 'WowSuchRicky (Signal)`). With the Discord bridge however, that is not the case. I find this a little bit confusing due to some folks having repeat usernames across multiple platforms.

It would be great if we could also suffix messages/chats from discord with (Discord) or similar. 

I do realize this bridge puts the Discord conversations into their own "Space" which is awesome, so I completely understand if we just want to stick to that philosophically :)

**Comment by tulir** [comment]
Displaynames are configurable in all mautrix bridges https://github.com/mautrix/discord/blob/main/example-config.yaml#L70-L77

**Comment by NathanC** [comment]
@tulir I updated this config, and it worked for new users-- but the old users don't get changed to include the suffix. Is there any way I can can force a name update?
