### ISSUE TITLE
Raise the reaction power level to admin when it's forbidden on discord side.

### ISSUE THREAD

**Issue by JokerGermany** [mautrix/discord#30]
When you send a reaction which is forbidden in the discord room, you get this message:
`⚠ Your reaction may not have been bridged: HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}`

Would be great if you could raise the needed power level for reactions to 100 (Admin), if reactions on the discord side are forbidden.
( In my opinion the best solution would be to forbid reactions in the matrix room, too. But i don't think there is an option for that in matrix)

**Comment by tulir** [comment]
Permissions aren't bridged yet
