### ISSUE TITLE
login fail 400 Bad Request

### ISSUE THREAD

**Issue by Hagbear** [mautrix/discord#38]
Hi, i try the discord bridge for the first time, but i can not log in.
After I scan the QR code and allow login in the discord app, i get an Error from the bridge bot.
Error logging in: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "XXX", "captcha_service": "hcaptcha", "captcha_rqdata": XXX}
what i do wrong?

**Comment by Hagbear** [comment]
with login-token it worked

**Comment by bboyles303** [comment]
I'm getting the same error on the QR method. login-token just results in an immediate "Message deleted by Discord bridge bot". Is there some fix for the QR method as this would be the easiest for my users?

**Comment by morguldir** [comment]
Did you put the token after the command like this? `login-token $token`

**Comment by bboyles303** [comment]
@morguldir That worked, thanks. I guess I missed that. Still the QR method would be a lot easier for some of my users. Hoping we can get a solution there.

**Comment by shufuwa** [comment]
same issue.
