### ISSUE TITLE
Load all DMs (and ideally history)

### ISSUE THREAD

**Issue by NathanC** [mautrix/discord#41]
I've set up the bridge, and a few recent DMs appeared, but the rest didn't. I have no way to message people I haven't messaged in a while, or friends, without first messaging them on Discord.

Is it possible to load all DMs? What about including history? Even if history isn't possible, loading all the main DMs in the list would be very helpful.

Thanks!

**Comment by vijfhoek** [comment]
I think a good first step would be having a `!discord search` functionality, like mautrix/whatsapp and mautrix/telegram, allowing you to start DMs using the bridge bot

**Comment by tulir** [comment]
`startup_private_channel_create_limit` already exists for creating all DMs
