### ISSUE TITLE
Users cannot join room on Dendrite instances

### ISSUE THREAD

**Issue by Salastil** [mautrix/discord#43]
Dendrite version: 0.10.7
PostgreSQL: 12.9
OS: Ubuntu 22.04.1 LTS aarch64
Docker: No
Built against: https://github.com/mautrix/discord/commit/f53975cc91e3c643a722adf0d3e0dfb98d0127a2

```
[Nov 11, 2022 03:35:20] [Matrix/@discord_399745824239910922:matrix.salastil.com/DEBUG] req #555 (/v3/rooms/!iaYIQgQgQ5wsTFDW:matrix.salastil.com/join) completed in 12.703124ms with status 500 and 161 bytes of application/json body         
[Nov 11, 2022 03:35:20] [Portal/782097359575187546/WARN] Failed to send message 1040469751052374036 to matrix: failed to ensure joined: failed to POST /_matrix/client/v3/rooms/!iaYIQgQgQ5wsTFDW:matrix.salastil.com/join: 500 Internal Server
 Error
``` 
The bridge _IS_ active, it detects chat from the various rooms and tries inviting the respective accounts but it throws an error that I have posted above. Messages outbound from Matrix reach the Discord room and if I talk in Discord my own account joins the room and I see it. A curious edge case is that a Discord bot did successfully join a room and is spamming away properly. There seems to be an existing bug report regarding this issue on the Dendrite Github: https://github.com/matrix-org/dendrite/issues/2696 I can't really be sure what is the cause of the issue, Dendrite or the Mautrix software.

**Comment by tulir** [comment]
Internal server errors are caused by whatever is throwing the internal server error in most cases.
