### ISSUE TITLE
Mautrix-discord Does Not Bridge Certain Messages from Avrae to Matrix

### ISSUE THREAD

**Issue by emassey0135** [mautrix/discord#44]
I set up this bridge on my homeserver with Synapse and logged in to my Discord account, and I could bridge guilds and it was sending and receiving messages. However, it would not bridge certain messages from Avrae, a Discord bot for playing Dungeons and Dragons, to Matrix correctly. Dice rolls from Avrae were transmitted fine, as were messages from other Discord users, but some messages from Avrae, including spell descriptions and the character's spellbook, were not bridged or only partially bridged. I found the same problem in bitlbee-discord, but both purple-discord and mx-puppet-discord bridge these messages correctly, so it seems like mautrix-discord has a problem with certain types or representations of messages, and I am not sure how to view raw Discord message data for what Avrae is sending, except by looking at Avrae's source code. I did not notice anything odd in the logs from these messages. To test this issue, [add Avrae to a server](https://invite.avrae.io) and type "!spell shatter" while the server is bridged to Matrix.

**Comment by tulir** [comment]
Probably #49
