### ISSUE TITLE
The bridge's rooms and dm are set up so that no one can write...is that a bug or is it?

### ISSUE THREAD

**Issue by raymand211092** [mautrix/discord#5]
[Portal/404105683336953866/WARN] failed to send message "986293902438961192" to matrix: failed to PUT /_matrix/client/v3/rooms/!bwFGTNqUAPUCXirfyL:mx.grupotd.nat.cu/send/m.room.message/mautrix-go_1655221190874482259_2: M_FORBIDDEN (HTTP 403): You don't have permission to post that to the room. user_level (0) < send_level (1)

![image](https://user-images.githubusercontent.com/50679989/173661405-3c4aeb9a-a6e8-4d0d-806b-baf51ffa0870.png)

**Comment by tulir** [comment]
The bridge doesn't currently set power levels at all, so that's probably something on your side
