### ISSUE TITLE
Discord emoji name should be visible to Matrix clients in m.reaction events

### ISSUE THREAD

**Issue by ToyKeeper** [mautrix/discord#50]
When users post reactions on Discord, they have a raw value (unicode or image URL) and a name... but after bridging, only the raw value is visible to Matrix clients.  Can this be added to the bridged events somehow?

This can be worked around for unicode emojis by giving the client a unicode database, but that approach doesn't work for custom emojis.  For example, when someone posts a ":doggohaha:" reaction on Discord, the Matrix client sees this:

```
{
'type': 'm.reaction',
'room_id': '!TibkLtkYVyvLSsDiKy:example.com',
'sender': '@discord_1234567890:example.com',
'content': {
  'm.relates_to': {
    'rel_type': 'm.annotation',
    'event_id': '$1idu7_ANjXYJSYhnzG4ztxJVlbeSgl_6TVP2vcYYLTQ',
    'key': 'mxc://example.com/QtEIYsdyBqeFsKVpLxXsRgey'
  }
},
'origin_server_ts': 1671560859601,
'unsigned': {'age': 1439742},
'event_id': '$OKpLBI5LsdihnX_sEEw7iVC3r-HAsawj61qXEFGTm9w',
'user_id': '@discord_1234567890:example.com',
'age': 1439742
}
```

Could an extra field be added, perhaps, containing Discord's emojiName string?  Perhaps after `'key':'mxc://...'`, it could have a `'title':'doggohaha'` or perhaps a `'body':'doggohaha'` and `'format':'text/plain'` or something?  Or, to keep the m.relates_to within spec, perhaps it should be content.title instead of content.m.relates_to.title?  I'm not sure what the best place is for it, but it should be included in the event somewhere.

The name is bridged properly when custom emojis are used in the middle of a regular message though...  for example, `'formatted_body':'Here is Pikachu laughing: <img data-mx-emoticon src="mxc://myserver/YnhtWwlKtWFpDCsOZidLbhVT" alt=":pikalol:" title=":pikalol:" height="32"/>'`  As far as I can tell, the name is only missing in reaction events.

**Comment by JokerGermany** [comment]
The Problem in this case is client side:
If you use Element, ask here:
https://github.com/vector-im/element-meta/issues/266

**Comment by JokerGermany** [comment]
You can see the emoji by changing the link like this in the browser:
https://example.com/_matrix/media/r0/download/example.com/QtEIYsdyBqeFsKVpLxXsRgey

**Comment by ToyKeeper** [comment]
@JokerGermany Thanks, but this issue is about the name, not the image.  This is unrelated to Element, or how Element displays reactions.

I can expand the mxc URI to get a link to the downloaded image and see what the emoji looks like... but there doesn't seem to be a way to get the name, because that data isn't included in the m.reaction event.  The name field is important for plain-text clients and for logging and grepping and accessibility and for extra context about what an emoji means, but it isn't sent as part of the reaction events yet.

The Mautrix documentation specifies exactly what data is sent for each event, and for m.reaction events, it only has one field for the emoji payload -- content.m.relates_to.key.  This holds the image URI.  Mautrix gets the title from Discord and stores it in an internal variable called emojiName, but there is no event field to transmit that variable to Matrix... yet.
