### ISSUE TITLE
Some emoji reactions cannot be bridged

### ISSUE THREAD

**Issue by robintown** [mautrix/discord#58]
To reproduce, react to a message with the trans flag:

![Screenshot 2023-02-18 at 14-59-35 Element 2 rolls](https://user-images.githubusercontent.com/48614497/219887107-81013573-0244-45d6-83d1-729b0040cf1b.png)

**Comment by kimabjorkede** [comment]
Same issue here when `custom_emoji_reactions: true` is on.
