### ISSUE TITLE
Reply messages from Discord to Matrix not showing in Element Android

### ISSUE THREAD

**Issue by Sakul6499** [mautrix/discord#59]
When someone replies to a message on Discord's side, the message won't be rendered correctly on Element Android (`v1.5.25 [40105251] (G-f74a885a)`).
I am unsure if this is a bug with Element Android App or the bridge missing out on information.
The message does show up properly on Element Web (`v.1.11.24-rc.1`) and Desktop (Windows, `v.1.11.23`).

Replying from Matrix to Discord works without problem.
Furthermore, when trying to Reply to such an "empty reply" the message **is shown** in the preview above the input field.
The `content.body` field is set correctly in either case in the Source View, however compared to Replies on Matrix rooms the `content.format` and `content.formatted_body` fields seem to be missing.

> My best guess is the Android App (and potentially other clients too) expect this field for some reason.  
> This _may_ also be an **issue with other bridges**. I've previously used [mx-puppet-discord](https://github.com/matrix-discord/mx-puppet-discord) where this didn't occur.

I've made a demonstration to show the problem more clearly.  
If this is the example chat (first and third message send from Discord, second and fourth send from Matrix):

![matrix_chat](https://user-images.githubusercontent.com/13678392/220673335-6d8d796d-6975-46f7-8031-b4b540219a84.jpg)

The reply (third message) appears to be empty. However, looking at the Source reveals:

```json
{
  "type": "m.room.message",
  "sender": "@discord_592416130505900062:matrix.sakul-flee.de",
  "content": {
    "body": "This is a reply from Discord.",
    "com.beeper.linkpreviews": [],
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$_8I8alZwYcraci4JP2TvqNJ6WobA_Lk7gDp2Rroufss"
      }
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1677079983899,
  "unsigned": {
    "age": 80
  },
  "event_id": "$qvl5uBTOiaC6PdTsVybhxEDHz8Eljjn3aA8HUozfDXs",
  "room_id": "!YAHAhcBAAcyKmOhdFg:matrix.sakul-flee.de"
}
``` 

In comparison, the reply from Matrix (fourth message) shows this:

```json
{
  "type": "m.room.message",
  "sender": "@sakulflee:matrix.sakul-flee.de",
  "content": {
    "msgtype": "m.text",
    "body": "> <@discord_592416130505900062:matrix.sakul-flee.de> This is a reply from Discord.\n\nThis is a reply from Matrix.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!YAHAhcBAAcyKmOhdFg:matrix.sakul-flee.de/$qvl5uBTOiaC6PdTsVybhxEDHz8Eljjn3aA8HUozfDXs?via=matrix.sakul-flee.de\">In reply to</a> <a href=\"https://matrix.to/#/@discord_592416130505900062:matrix.sakul-flee.de\">@discord_592416130505900062:matrix.sakul-flee.de</a><br>This is a reply from Discord.</blockquote></mx-reply>This is a reply from Matrix.",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$qvl5uBTOiaC6PdTsVybhxEDHz8Eljjn3aA8HUozfDXs"
      }
    }
  },
  "origin_server_ts": 1677079991992,
  "unsigned": {
    "age": 86,
    "transaction_id": "m1677079991283.185"
  },
  "event_id": "$6yEL7nFr4IL_A6M3EBw4-Dwpc1KdPZyIS_c7KoI6xw8",
  "room_id": "!YAHAhcBAAcyKmOhdFg:matrix.sakul-flee.de"
}
```

And if we e.g. try to reply to the empty message, the message preview actually shows the text:

![reply_text](https://user-images.githubusercontent.com/13678392/220675066-15301823-98ef-4750-9173-e667335232b7.jpg)

If more information and/or debugging is needed I am happy to provide given instructions :)
I could also attempt fixing it myself if I know where to start ...
With kind regards, amazing work! ❤️

**Comment by tulir** [comment]
That looks like a client bug. Reply fallbacks a legacy thing, reply-aware clients aren't allowed to depend on them.
