### ISSUE TITLE
Show "Category" for room

### ISSUE THREAD

**Issue by dzg** [mautrix/discord#61]
I would like to see the "Category" of a room in the name of the bridged room – or at least the option to rename manually. (Beeper said "forbidden" when trying to edit room name via chat settings > advanced > devtools.)

As you can see in attachment, on our server we have many rooms called "general talk" but they belong to different **Categories.**

<img width="181" alt="image" src="https://user-images.githubusercontent.com/466557/221249721-333c9368-d5f8-4f87-81df-744950f83bba.png">

But in Beeper, the room is called "general talk" regardless of category.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/466557/221249699-7724d66a-2a8a-422e-868c-a7d0466918f3.png">

In this example it would be much better if the room in Beeper was called "MS-23-Apr#project-info"

**Comment by tulir** [comment]
Your Beeper support room is the correct place to send feature requests for Beeper (which you already did, so this is a duplicate 🙃)

The bridge already supports [changing the name format](https://github.com/mautrix/discord/blob/main/example-config.yaml#L85-L92), but it's in the bridge config so can't be changed at runtime. You can make yourself admin in the room to change the name, but the bridge may randomly change it back and doing that voids your Beeper warranty (`!discord set-pl 99`).
