### ISSUE TITLE
Shared space when two users bridge the same guild

### ISSUE THREAD

**Issue by lucas-dclrcq** [mautrix/discord#62]
When two users bridge the same guild, the second user will not receive the channel invites, only the first user to bridge.

If the first user to bridge invite the second one to the created space, everything will work as expected.

It would be great to be able to auto-invite an user to an already created space or at least to advertise on bridging that the user should ask to be invited.

**Comment by kimabjorkede** [comment]
I hope this gets implemented. It's almost unusable for multiple users on a homeserver without it.
Keep up the good work!
