### ISSUE TITLE
`unbridge` causes problems with channel detection later on.

### ISSUE THREAD

**Issue by GamePlayer-8** [mautrix/discord#69]
Heyo,

After executing `!discord unbridge` the bot leaves the room & unbridging the channel ID from the discord server.

Although later bot can't find channels from that discord server - needs to be kicked in order to make him work again on that discord server.

**Comment by tulir** [comment]
What did you do exactly and what do you mean by "can't find channels from that discord server"?

**Comment by GamePlayer-8** [comment]
> what do you mean by "can't find channels from that discord server"?
It just says `Channel not found.`.

**Comment by tulir** [comment]
I found a few bugs in unbridging and bridging, but none of them cause that issue. Are you sure you didn't use some dangerous command like `delete-all-portals`?

**Comment by GamePlayer-8** [comment]
I'm not.

I just compiled the master branch with `go` & it `go`es to that problem.
