### ISSUE TITLE
Docs: Self-Bot against Discord TOS?

### ISSUE THREAD

**Issue by IngwiePhoenix** [mautrix/discord#78]
Hello!

It'd be nice if there was a mention in the docs regarding the Discord ToS' stance towards using third-party clients deemed as "self-bots".

That said, it has been a hot minute since I last read the Discord tos to be honest, but it'd be something you might want to add - even if only in a single sentence or alike.

Thanks and kind regards,
Ingwie

**Comment by faszkany** [comment]
I know what you are

**Comment by Damaj301damaj-lol** [comment]
> I know what you are

Unrelated + off-topic + threatening, not the person you should be in a github issue tracker
