### ISSUE TITLE
Does not work on Conduit

### ISSUE THREAD

**Issue by obj-obj** [mautrix/discord#80]
Leaving this bug report here because it might be a `mautrix-discord` issue and not a conduit one

Basically the issue is a permission denied when the appservice tries to get users to join a bridged channel room.

Manually giving invites to bridged users makes them join the room when the next message is sent (and bridging then works for that specific user in that specific channel. This might be solvable if the discord bridge bot (owner of the rooms) invites the bridged users before the appservice tries to get them to join the rooms

DMs work fine, but servers do not

Issue on conduit: https://gitlab.com/famedly/conduit/-/issues/336

**Comment by obj-obj** [comment]
![image](https://github.com/mautrix/discord/assets/57120300/4a6779b9-cb6c-4387-b5d1-56cb149d8305)

**Comment by tulir** [comment]
Sounds like a Conduit bug

**Comment by obj-obj** [comment]
@tulir do the puppeting users join the spaces before trying to join the bridged rooms?

**Comment by tulir** [comment]
No

**Comment by obj-obj** [comment]
![image](https://github.com/mautrix/discord/assets/57120300/c59c4e3e-958a-47db-a5cd-0cde5bc9bf5f)

**Comment by tulir** [comment]
Synapse should return `M_FORBIDDEN`, it sounds like Conduit returns an internal server error with `M_UNKNOWN` which is wrong.

**Comment by obj-obj** [comment]
Yeah but that would still result in the puppeted discord users not being able to join the bridged room, right?

**Comment by tulir** [comment]
No, the ghosts get invited and the join is retried if the first join fails with `M_FORBIDDEN`
