### ISSUE TITLE
Embeds are edited into edited matrix-side messages with replies

### ISSUE THREAD

**Issue by tezlm** [mautrix/discord#86]
- As of the latest commit ([35f534a](https://github.com/mautrix/discord/commit/35f534affa2bc6ba579d419b0a3ee873d5e9f554))
- If you have a message sent from matrix
- And it is replying to another message
- And you edit the message
- Then the reply embed is edited into the message

Example:

![image](https://user-images.githubusercontent.com/56274831/236636186-4348080d-ab2b-4885-b03c-d90f81f88886.png)

**Comment by tulir** [comment]
Which client is that?

**Comment by tezlm** [comment]
cinny
