### ISSUE TITLE
Backfilling portal after the fact

### ISSUE THREAD

**Issue by MagicRB** [mautrix/discord#89]
Not sure if this possible, but would be nice if I could force a backfill in a specific portal, ideally in a specific time range too. I know on room creation it is possible, but for big guilds I'd like to backfill in specific chunks to get the messages i want and also not to trigger discord. If you point me in the right direction I'll attempt to throw something together myself.

**Comment by tulir** [comment]
You can't insert messages anywhere else than the end of the room, which usually means you can only backfill right after room creation (when there are no messages in the room) and missed messages on startup.

**Comment by tulir** [comment]
There was (https://github.com/matrix-org/matrix-spec-proposals/pull/2716), but they decided to do the gitter migration in a different way and gave up on proper backfilling. The synapse implementation never got far enough to be properly usable

**Comment by PoneyClairDeLune** [comment]
I have a related question. The Discord bridge doesn't seem to be starting a backfill after creation (`dock.mau.dev/mautrix/discord`, `4699cf793d38`), and there is no way to enforce a backfill either. What could be done in this case?
