### ISSUE TITLE
Replies to messages in servers not triggering notification/highlight of message

### ISSUE THREAD

**Issue by elgatopanzon** [mautrix/discord#92]
I tested this functionality in both Element and Schildichat by having replies sent to my messages on discord bridged rooms, and having replies sent to my messages on Matrix rooms. In the matrix room, replies show up normally:

![Screenshot_select-area_20230603165424](https://github.com/mautrix/discord/assets/133258481/d9d6c3e9-bbfd-4c35-8df5-9fc9daa5ac16)

However in a discord bridged channel, replies don't work at all and are treated like normal messages:

![Screenshot_select-area_20230603171125](https://github.com/mautrix/discord/assets/133258481/207f2c18-9ef5-4fc3-99d7-4a8f5e20b24a)

My notification settings have mentions enabled and I can't figure out why this only applies to discord bridged rooms?

**Comment by tulir** [comment]
Reply fallbacks are extremely legacy and probably won't be added to this bridge. Intentional mentions are already implemented. I'm not sure what's the client implementation status exactly, but I'd assume element web should at least enable them soon.
