### ISSUE TITLE
Can't accept or decline direct message invite 

### ISSUE THREAD

**Issue by wangwillian0** [mautrix/discord#93]
Trying to accept invite:
> level=error msg="Failed to join room" error="1 : InputRoomEvents auth failed: InputRoomEventsResponse: eventauth: \"@...\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" room_id="!..." servers="[...]" user_id="@..."

Rejecting invite:
> level=error msg="Failed to leave room" error="user \"@...\" is not joined to the room (membership is \"leave\")" room_id="!..." user_id="@..."

I'm using Dendrite. Maybe related to https://github.com/mautrix/whatsapp/issues/529?

**Comment by tulir** [comment]
Dendrite has state bugs
