### ISSUE TITLE
Messages stopped coming and being sent from bridged channels

### ISSUE THREAD

**Issue by elgatopanzon** [mautrix/discord#97]
I've been running mautrix-discord bridge without issues for around a month now. Until last night, when I noticed that messages stopped being delivered to bridged channels and messages I sent from them also stopped being sent out to the discord channel. I observed the following things:

* Typing notifications are still sent, so in an active channel it shows users typing away like crazy
* Users are still invited to the bridged channel like normal
* The message body that is supposed to go into the channel doesn't appear in the bot's logs, while ones which do go in successfully (from other channels, because it seems random) do show up in the logs. So I assume the missing messages are not picked up and is never sent to the server in the first place

Currently some channels on some servers despite being active on Discord are not handling any messages, while some even on the same servers are functioning perfectly fine. There doesn't appear to be any rhyme or reason for why some channels work and others don't. I also can't see any errors in the logs that indicate what the problem might be.

Things I've tried:

* Restarting the bridge multiple times (it seems to restore messages for a few minutes, then it just randomly stops)
* Unbridging and re-bridging the channels
* Unbridging and re-bridging the guild
* Using the `disconnect` and `reconnect` commands
* Restarting my Matrix server

**Comment by elgatopanzon** [comment]
So far downgrading to docker tag `v0.5.0` has resolved this issue for me.

**Comment by storm1er** [comment]
Issues still seem to be present on v0.6.5 :(
